name: pull requests

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  pull-requests:
    uses: swiss-architecture-knife/.github/.github/workflows/pull-requests.yaml@main
